name: 错误报告
description: 创建错误报告以帮助我们改进
labels: bug
body:
  - type: textarea
    id: error
    attributes:
      label: 错误描述
      description: 对错误的清晰简洁描述
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 复现步骤
      placeholder: |
        1. 打开 Clash .NET 软件
        2. ...
    validations:
      required: true
  - type: checkboxes
    id: captcha
    attributes:
      label: 真人验证
      description: 请勾选下面的选框.
      options:
        - label: 请确认在提交Issue前你已经看过readme并且搜索和阅读过相关问题。否则你的Issue会被标记为重复并立即关闭。
          required: true
  - type: textarea
    id: log
    attributes:
      label: 日志
      description: 强烈建议附上任何在 `logs` 文件夹下面的日志
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: 操作环境
      render: txt
      placeholder: |
        操作系统：[Windows 10 x64 Professional Workstation 20H2 19042.928]
        软件版本：[1.2.8]
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: 额外信息
      description: >
        下面的文本框中你可以附上跟 issue 相关的截图、文件
